version: "3"

services:
  kafka:
    container_name: "social-net-kafka"
    image: confluentinc/cp-kafka:7.6.0
    hostname: social-net-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://social-net-kafka:29092,PLAINTEXT_HOST://social-net-kafka:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@social-net-kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://social-net-kafka:29092,CONTROLLER://social-net-kafka:29093,PLAINTEXT_HOST://social-net-kafka:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_JMX_PORT: 9997
    ports:
      - "9092:9092"
    networks:
      - social-net-network

  kafka-ui:
    container_name: "social-net-kafka-ui"
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'social-net-kafka:29092'
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    ports:
      - "9091:8080"
    networks:
      - social-net-network

  init-kafka:
    container_name: "social-net-init-kafka"
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    networks:
      - social-net-network
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server social-net-kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server social-net-kafka:29092 --create --if-not-exists --topic post_events --replication-factor 1 --partitions 2

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server social-net-kafka:29092 --list
      "

networks:
  social-net-network:
    name: "social-net-network"
    driver: bridge