version: '3'
services:
  post-db-setup:
    image: postgres:latest
    hostname: post_database
    container_name: post-db-setup
    restart: always
    environment:
      POSTGRES_USER: postiniter
      POSTGRES_PASSWORD: qwerty123456
      POSTGRES_DB: post_db
    volumes:
      - post-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postiniter", "-d", "post_db"]
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - social-net-network

  post-db-migration:
    image: migrate/migrate
    container_name: post-db-migration
    restart: on-failure
    depends_on:
      - post-db-setup
    volumes:
      - ./postService/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postiniter:qwerty123456@post_database:5432/post_db?sslmode=disable", 
      "-verbose", "up"
    ]
    networks:
      - social-net-network
  
  post-service:
    hostname: post_service
    restart: on-failure
    build:
      context: ./
      dockerfile: ./postService/post.Dockerfile
    ports:
      - "50052:50052"
      - "8081:8081"
    depends_on:
      - post-db-migration
    environment:
      - DB_HOST=post_database
      - DB_PORT=5432
      - DB_USER=postiniter
      - DB_PASSWORD=qwerty123456
      - DB_NAME=post_db
    networks:
      - social-net-network

  stats-db-setup:
    image: clickhouse/clickhouse-server
    hostname: stats_database
    restart: always
    volumes:
      - stats-db-data:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: wget --spider -q stats_database:8123/ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - social-net-network

  stats-db-migration:
    image: migrate/migrate
    container_name: stats-db-migration
    restart: on-failure
    depends_on:
      stats-db-setup:
        condition: service_healthy
    volumes:
      - ./statisticsService/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "clickhouse://default:@stats_database:9000/default",
      "-verbose", "up"
    ]
    networks:
      - social-net-network

  statistics-service:
    hostname: statistics_service
    restart: on-failure
    build:
      context: ./
      dockerfile: ./statisticsService/statistics.Dockerfile
    depends_on:
      - stats-db-setup
      - stats-db-migration
    ports:
      - "8083:8083"
      # - "50053:50053"
      # - "8082:8082"
    networks:
      - social-net-network

volumes:
  post-db-data:
  stats-db-data:

networks:
  social-net-network:
    name: "social-net-network"
    driver: bridge