version: '3'
services:
  post-db-setup:
    image: postgres:latest
    hostname: post_database
    container_name: post-db-setup
    restart: always
    environment:
      POSTGRES_USER: postiniter
      POSTGRES_PASSWORD: qwerty123456
      POSTGRES_DB: post_db
    volumes:
      - post-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postiniter", "-d", "post_db"]
        interval: 5s
        timeout: 5s
        retries: 5
    networks:
      - social-net-network

  post-db-migration:
    image: migrate/migrate
    container_name: post-db-migration
    restart: on-failure
    depends_on:
      post-db-setup:
        condition: service_healthy
    volumes:
      - ./postService/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postiniter:qwerty123456@post_database:5432/post_db?sslmode=disable", 
      "-verbose", "up"
    ]
    networks:
      - social-net-network
  
  post-service:
    hostname: post_service
    restart: on-failure
    build:
      context: ./
      dockerfile: ./postService/post.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - post-db-migration
    environment:
      - DB_HOST=post_database
      - DB_PORT=5432
      - DB_USER=postiniter
      - DB_PASSWORD=qwerty123456
      - DB_NAME=post_db
    networks:
      - social-net-network

volumes:
  post-db-data:

networks:
  social-net-network:
    name: "social-net-network"