// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: stat_v1/statService.proto

package stat_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	// Returns the total number of views and likes for a specific post
	TotalViewsLikes(ctx context.Context, in *TotalViewsLikesRequest, opts ...grpc.CallOption) (*TotalViewsLikesResponse, error)
	// Returns the top N posts by number of likes or views
	TopNPosts(ctx context.Context, in *TopNPostsRequest, opts ...grpc.CallOption) (*TopNPostsResponse, error)
	// Returns the top N users with the most likes across all their posts.
	TopNUsers(ctx context.Context, in *TopNUsersRequest, opts ...grpc.CallOption) (*TopNUsersResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) TotalViewsLikes(ctx context.Context, in *TotalViewsLikesRequest, opts ...grpc.CallOption) (*TotalViewsLikesResponse, error) {
	out := new(TotalViewsLikesResponse)
	err := c.cc.Invoke(ctx, "/stat_v1.StatisticsService/TotalViewsLikes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) TopNPosts(ctx context.Context, in *TopNPostsRequest, opts ...grpc.CallOption) (*TopNPostsResponse, error) {
	out := new(TopNPostsResponse)
	err := c.cc.Invoke(ctx, "/stat_v1.StatisticsService/TopNPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) TopNUsers(ctx context.Context, in *TopNUsersRequest, opts ...grpc.CallOption) (*TopNUsersResponse, error) {
	out := new(TopNUsersResponse)
	err := c.cc.Invoke(ctx, "/stat_v1.StatisticsService/TopNUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility
type StatisticsServiceServer interface {
	// Returns the total number of views and likes for a specific post
	TotalViewsLikes(context.Context, *TotalViewsLikesRequest) (*TotalViewsLikesResponse, error)
	// Returns the top N posts by number of likes or views
	TopNPosts(context.Context, *TopNPostsRequest) (*TopNPostsResponse, error)
	// Returns the top N users with the most likes across all their posts.
	TopNUsers(context.Context, *TopNUsersRequest) (*TopNUsersResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (UnimplementedStatisticsServiceServer) TotalViewsLikes(context.Context, *TotalViewsLikesRequest) (*TotalViewsLikesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalViewsLikes not implemented")
}
func (UnimplementedStatisticsServiceServer) TopNPosts(context.Context, *TopNPostsRequest) (*TopNPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopNPosts not implemented")
}
func (UnimplementedStatisticsServiceServer) TopNUsers(context.Context, *TopNUsersRequest) (*TopNUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopNUsers not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_TotalViewsLikes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalViewsLikesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).TotalViewsLikes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_v1.StatisticsService/TotalViewsLikes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).TotalViewsLikes(ctx, req.(*TotalViewsLikesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_TopNPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopNPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).TopNPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_v1.StatisticsService/TopNPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).TopNPosts(ctx, req.(*TopNPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_TopNUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopNUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).TopNUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_v1.StatisticsService/TopNUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).TopNUsers(ctx, req.(*TopNUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stat_v1.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TotalViewsLikes",
			Handler:    _StatisticsService_TotalViewsLikes_Handler,
		},
		{
			MethodName: "TopNPosts",
			Handler:    _StatisticsService_TopNPosts_Handler,
		},
		{
			MethodName: "TopNUsers",
			Handler:    _StatisticsService_TopNUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stat_v1/statService.proto",
}
