// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: stat_v1/statService.proto

package stat_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotalViewsLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId int64 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
}

func (x *TotalViewsLikesRequest) Reset() {
	*x = TotalViewsLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalViewsLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalViewsLikesRequest) ProtoMessage() {}

func (x *TotalViewsLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalViewsLikesRequest.ProtoReflect.Descriptor instead.
func (*TotalViewsLikesRequest) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{0}
}

func (x *TotalViewsLikesRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type TotalViewsLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId     int64  `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	TotalViews uint64 `protobuf:"varint,2,opt,name=totalViews,proto3" json:"totalViews,omitempty"`
	TotalLikes uint64 `protobuf:"varint,3,opt,name=totalLikes,proto3" json:"totalLikes,omitempty"`
}

func (x *TotalViewsLikesResponse) Reset() {
	*x = TotalViewsLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalViewsLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalViewsLikesResponse) ProtoMessage() {}

func (x *TotalViewsLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalViewsLikesResponse.ProtoReflect.Descriptor instead.
func (*TotalViewsLikesResponse) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{1}
}

func (x *TotalViewsLikesResponse) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TotalViewsLikesResponse) GetTotalViews() uint64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *TotalViewsLikesResponse) GetTotalLikes() uint64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

type TopNPostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N     int64  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *TopNPostsRequest) Reset() {
	*x = TopNPostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNPostsRequest) ProtoMessage() {}

func (x *TopNPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNPostsRequest.ProtoReflect.Descriptor instead.
func (*TopNPostsRequest) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{2}
}

func (x *TopNPostsRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *TopNPostsRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

// General case since likes and vies are both numbers
type TopNPosts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId   uint32 `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Number   uint64 `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"` // number of likes or views, whatever
}

func (x *TopNPosts) Reset() {
	*x = TopNPosts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNPosts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNPosts) ProtoMessage() {}

func (x *TopNPosts) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNPosts.ProtoReflect.Descriptor instead.
func (*TopNPosts) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{3}
}

func (x *TopNPosts) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *TopNPosts) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopNPosts) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TopNPosts) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type TopNPostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopNPosts []*TopNPosts `protobuf:"bytes,1,rep,name=topNPosts,proto3" json:"topNPosts,omitempty"`
}

func (x *TopNPostsResponse) Reset() {
	*x = TopNPostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNPostsResponse) ProtoMessage() {}

func (x *TopNPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNPostsResponse.ProtoReflect.Descriptor instead.
func (*TopNPostsResponse) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{4}
}

func (x *TopNPostsResponse) GetTopNPosts() []*TopNPosts {
	if x != nil {
		return x.TopNPosts
	}
	return nil
}

type TopNUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int64 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *TopNUsersRequest) Reset() {
	*x = TopNUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNUsersRequest) ProtoMessage() {}

func (x *TopNUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNUsersRequest.ProtoReflect.Descriptor instead.
func (*TopNUsersRequest) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{5}
}

func (x *TopNUsersRequest) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

// Users can be measured only by likes without views
type TopNUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Number   uint64 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"` // number of likes
}

func (x *TopNUsers) Reset() {
	*x = TopNUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNUsers) ProtoMessage() {}

func (x *TopNUsers) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNUsers.ProtoReflect.Descriptor instead.
func (*TopNUsers) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{6}
}

func (x *TopNUsers) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TopNUsers) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type TopNUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopNUsers []*TopNUsers `protobuf:"bytes,1,rep,name=topNUsers,proto3" json:"topNUsers,omitempty"`
}

func (x *TopNUsersResponse) Reset() {
	*x = TopNUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stat_v1_statService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNUsersResponse) ProtoMessage() {}

func (x *TopNUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_v1_statService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNUsersResponse.ProtoReflect.Descriptor instead.
func (*TopNUsersResponse) Descriptor() ([]byte, []int) {
	return file_stat_v1_statService_proto_rawDescGZIP(), []int{7}
}

func (x *TopNUsersResponse) GetTopNUsers() []*TopNUsers {
	if x != nil {
		return x.TopNUsers
	}
	return nil
}

var File_stat_v1_statService_proto protoreflect.FileDescriptor

var file_stat_v1_statService_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x61,
	0x74, 0x5f, 0x76, 0x31, 0x22, 0x30, 0x0a, 0x16, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x65,
	0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x17, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x56,
	0x69, 0x65, 0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x54, 0x6f, 0x70,
	0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x6f, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x45, 0x0a, 0x11, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x4e, 0x50,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61,
	0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x09,
	0x74, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x20, 0x0a, 0x10, 0x54, 0x6f, 0x70,
	0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x22, 0x3f, 0x0a, 0x09, 0x54,
	0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x11,
	0x54, 0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x09, 0x74, 0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54,
	0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x4e, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x32, 0xf1, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x65, 0x77,
	0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x65,
	0x77, 0x73, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76,
	0x31, 0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x72, 0x79, 0x2f, 0x53,
	0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x76, 0x31, 0x3b, 0x73, 0x74, 0x61, 0x74, 0x5f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stat_v1_statService_proto_rawDescOnce sync.Once
	file_stat_v1_statService_proto_rawDescData = file_stat_v1_statService_proto_rawDesc
)

func file_stat_v1_statService_proto_rawDescGZIP() []byte {
	file_stat_v1_statService_proto_rawDescOnce.Do(func() {
		file_stat_v1_statService_proto_rawDescData = protoimpl.X.CompressGZIP(file_stat_v1_statService_proto_rawDescData)
	})
	return file_stat_v1_statService_proto_rawDescData
}

var file_stat_v1_statService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_stat_v1_statService_proto_goTypes = []interface{}{
	(*TotalViewsLikesRequest)(nil),  // 0: stat_v1.TotalViewsLikesRequest
	(*TotalViewsLikesResponse)(nil), // 1: stat_v1.TotalViewsLikesResponse
	(*TopNPostsRequest)(nil),        // 2: stat_v1.TopNPostsRequest
	(*TopNPosts)(nil),               // 3: stat_v1.TopNPosts
	(*TopNPostsResponse)(nil),       // 4: stat_v1.TopNPostsResponse
	(*TopNUsersRequest)(nil),        // 5: stat_v1.TopNUsersRequest
	(*TopNUsers)(nil),               // 6: stat_v1.TopNUsers
	(*TopNUsersResponse)(nil),       // 7: stat_v1.TopNUsersResponse
}
var file_stat_v1_statService_proto_depIdxs = []int32{
	3, // 0: stat_v1.TopNPostsResponse.topNPosts:type_name -> stat_v1.TopNPosts
	6, // 1: stat_v1.TopNUsersResponse.topNUsers:type_name -> stat_v1.TopNUsers
	0, // 2: stat_v1.StatisticsService.TotalViewsLikes:input_type -> stat_v1.TotalViewsLikesRequest
	2, // 3: stat_v1.StatisticsService.TopNPosts:input_type -> stat_v1.TopNPostsRequest
	5, // 4: stat_v1.StatisticsService.TopNUsers:input_type -> stat_v1.TopNUsersRequest
	1, // 5: stat_v1.StatisticsService.TotalViewsLikes:output_type -> stat_v1.TotalViewsLikesResponse
	4, // 6: stat_v1.StatisticsService.TopNPosts:output_type -> stat_v1.TopNPostsResponse
	7, // 7: stat_v1.StatisticsService.TopNUsers:output_type -> stat_v1.TopNUsersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stat_v1_statService_proto_init() }
func file_stat_v1_statService_proto_init() {
	if File_stat_v1_statService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stat_v1_statService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalViewsLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalViewsLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNPostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNPosts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNPostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stat_v1_statService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopNUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stat_v1_statService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stat_v1_statService_proto_goTypes,
		DependencyIndexes: file_stat_v1_statService_proto_depIdxs,
		MessageInfos:      file_stat_v1_statService_proto_msgTypes,
	}.Build()
	File_stat_v1_statService_proto = out.File
	file_stat_v1_statService_proto_rawDesc = nil
	file_stat_v1_statService_proto_goTypes = nil
	file_stat_v1_statService_proto_depIdxs = nil
}
