---
openapi: 3.0.0
info:
  title: User Authentification API
  description: API for user registration, updating, and authentication
  version: 1.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user account
                password:
                  type: string
                  description: The password of the user account
              required:
                - username
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /update/:username:
    put:
      summary: Update an existing user
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: The username of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user
                surname:
                  type: string
                  description: The surname of the user
                birthday:
                  type: string
                  format: date
                  description: The birthday date of the user
                email:
                  type: string
                  description: The email of the user
                phone:
                  type: string
                  description: The phone number of the user
              required:
                - name
                - surname
                - birthday
                - email
                - phone
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /login:
    post:
      summary: Log in a user via username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user account
                password:
                  type: string
                  description: The password of the user account
              required:
                - username
                - password
      responses:
        '200':
          description: User authenticated successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  schemas:
    User:
      type: object
      required:
        - name
        - surname
        - birthday
        - email
        - phone
      properties:
        name:
          type: string
          description: The first name of the user
        surname:
          type: string
          description: The last name of the user
        birthday:
          type: string
          format: date
          description: The birthday of the user
        email:
          type: string
          format: email
          description: The email address of the user
        phone:
          type: string
          description: The phone number of the user
    RegistrationRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: The username of the user
        password:
          type: string
          description: The password of the user
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: The username of the user
        password:
          type: string
          description: The password of the user
