# This workflow will build a golang project

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    # Install dependencies
    - name: Install dependencies
      run: go work sync

    # # Build the Go project
    # - name: Build
    #   run: go build -v ./...

    # Run specific unit test - mainService
    - name: Run tests for main service
      run: go test ./mainService/pkg
      env:
        GOROOT: /opt/hostedtoolcache/go/1.22.3/x64

    # Run specific unit test - postService
    - name: Run tests for post service
      run: go test ./postService/pkg
      env:
        GOROOT: /opt/hostedtoolcache/go/1.22.3/x64

    # Run specific unit test - statisticsService
    - name: Run tests for statistics service
      run: go test ./statisticsService/pkg
      env:
        GOROOT: /opt/hostedtoolcache/go/1.22.3/x64